### ISSUE TITLE
Dangerouse word extraction

### ISSUE THREAD

**Issue by valerio-vaccaro** [n3s1us/bitcoin-seed-phrase-composer-with-dice#1]
The multiplications between two uniform variables (dices) is not a uniform distributed variable, this decrease drastically entropy of the generated mnemonic.

e.g for column you will have multiple combination for 6 and no one combination for 19 or 27

**Comment by pidark** [comment]
You are right I will change the extraction mode in selection of quadrants and sub-quadrants.

Now I put an alert in the README

**Comment by pidark** [comment]
Extraction mode changed now the words have the same probability, a double check and confirmation from you is always welcome.

**Comment by valerio-vaccaro** [comment]
much better, i suggest to shows the process you are following or some documents describe it in the readme.
