### ISSUE TITLE
24th word calculation drops 3 bit of entropy

### ISSUE THREAD

**Issue by valerio-vaccaro** [n3s1us/bitcoin-seed-phrase-composer-with-dice#2]
In a 24 words mnemonic there are 8 bit of checksum, a word is chosen using 11 bit of entropy. The actual methods ignore entropy for the 24th word (3 bit).

**Comment by pidark** [comment]
Quite right! For every 23 words there are 8 possible checksum words I added a further extraction. Fixed!
